name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Set Locale
      run: |
        sudo apt-get update && sudo apt-get install tzdata locales -y   
        sudo locale-gen ru_RU.UTF-8
        sudo locale-gen ru_RU
        locale -a

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: education/autograding@v1
      id: autograder
