name: Autograding Tests
'on':
  push:
    branches:
    - '*'
    - '!badges'
  workflow_dispatch:
  repository_dispatch:
permissions:
  checks: write
  actions: read
  contents: write
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Set Locale
      run: |
        sudo apt-get update && sudo apt-get install tzdata locales -y   
        sudo locale-gen ru_RU.UTF-8
        sudo locale-gen ru_RU
        locale -a

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: education/autograding@v1
      id: autograder

    ############################
    # Generate points bar badge
    - run: git checkout badges || git checkout -b badges
    - name: points bar
      uses: markpatterson27/points-bar@v1
      with:
        points: ${{ steps.autograder.outputs.points }}
        path: '.github/badges/points-bar.svg'
        label: 'Баллы'
    - name: Commit changes to points bar
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add '.github/badges/points-bar.svg'
        git commit -m "Add/Update points bar" || exit 0
        git push origin badges
